---
# Dfinr styles are released under the Creative Commons Attribution 4.0 International (CC BY 4.0) license.
# https://creativecommons.org/licenses/by/4.0/
#
# 'Since' is frequently misused for 'because'.
#
extends: existence
message: "Please verify that you've used 'since' to refer to time. Use 'because' to describe the reason for something. For example, \"It's been an hour since he left, because he had a flat tire.\""
link: https://dfinr.com/style-guide/
level: suggestion
ignorecase: true
tokens:
  - since
