---
# Based on work created and shared by Google and 
# used according to terms described in the Creative Commons 4.0 Attribution License.
# https://developers.google.com/terms/site-policies
extends: existence
message: "Please don't use punctuation in headings unless writing FAQ questions."
link: https://dfinr.com/style-guide/
level: warning
nonword: true
scope: heading
action:
  name: edit
  params:
    - remove
    - '.'
tokens:
  - '[a-z0-9][.](?:\s\s|$)'
