---
# Dfinr styles are released under the Creative Commons Attribution 4.0 International (CC BY 4.0) license.
# https://creativecommons.org/licenses/by/4.0/
#
# Suggests inclusive term alternatives.
extends: substitution
message: "Please consider using %s instead of '%s.'"
link: https://dfinr.com/style-guide/
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  blacklist(?:ed|ing|s)?: deny|denylist
  master: primary|main
  slave: secondary|replica|subordinate
  whitelist(?:ed|ing|s)?: allow|allowlist
