---
# Dfinr styles are released under the Creative Commons Attribution 4.0 International (CC BY 4.0) license.
# https://creativecommons.org/licenses/by/4.0/
#
extends: existence
message: "Avoid frequent use of blockquotes. Reserve blockquotes for important notes that require high visibility."
link: https://dfinr.com/style-guide/
level: suggestion
nonword: true
scope: raw
tokens:
  - '^>\s(.*$)'
