---
# Based on work created and shared by Microsoft and 
# used according to terms described in the Creative Commons 4.0 Attribution International License.
# https://github.com/MicrosoftDocs/microsoft-style-guide/lob/master/LICENSE
extends: existence
message: "If space is an issue in a range of numbers, such as in tables, use an en dash instead of a hyphen."
link: https://dfinr.com/style-guide/
level: warning
nonword: true
tokens:
  - '\b\d+\s?[-]\s?\d+\b'
